# Generated by Django 5.2.8 on 2025-11-24 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysissession',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='content',
        ),
        migrations.AddField(
            model_name='analysissession',
            name='title',
            field=models.CharField(default='Health Analysis', max_length=200),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='analysis_type',
            field=models.CharField(choices=[('vitamin_minerals', 'Vitamin & Minerals Intake'), ('exercise_routine', 'Weekly Exercise Routine'), ('food_quality', 'Weekly Food Quality'), ('sleep_quality', 'Sleep Quality & Habits'), ('stress_levels', 'Stress Levels & Daily Workload'), ('hydration', 'Hydration Levels'), ('mental_wellbeing', 'Mental Well-being Routine'), ('energy_levels', 'Daily Energy Levels'), ('meal_balance', 'Weekly Meal Balance'), ('digestion', 'Digestion & Gut Health'), ('calorie_intake', 'Daily Calorie Intake'), ('posture', 'Posture & Ergonomics'), ('exercise_balance', 'Cardio vs Strength Training Balance'), ('hormone_health', 'Hormone-supporting Lifestyle'), ('immune_health', 'Immune-supporting Habits'), ('productivity', 'Daily Productivity & Burnout Risk'), ('screen_time', 'Screen Time & Blue-light Exposure'), ('environmental_toxins', 'Environmental Toxins Exposure'), ('caffeine', 'Caffeine & Stimulant Consumption'), ('alcohol', 'Alcohol Intake & Lifestyle Balance'), ('menstrual_health', 'Menstrual Cycle Health'), ('mobility', 'Daily Mobility & Flexibility'), ('chronic_pain', 'Chronic Pain Patterns')], max_length=50),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.analysissession'),
        ),
    ]
